version: "2"

checks:
  argument-count:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 900
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 30
  similar-code:
    config:
      threshold: 40

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
      mass_threshold: 40
      languages:
        python:
          python_version: 3
      exclude_patterns:
      - "tests/link_tests.py"

  fixme:
    enabled: true
    config:
      strings:
      - BUG
      - FIXME
      - fixme
      - hack
      - TODO
      - XXX

exclude_patterns:
- "docs/"
- "!docs/conf.py"
- "tox.ini"
- "*.json"
- "*.png"
- "*.rst"
- "*.txt"
- "*.xml"
- "*.yml"
