---
default_install_hook_types:
  - commit-msg
  - pre-commit

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://gitlab.wikimedia.org/repos/ci-tools/commit-message-validator
    rev: v2.1.0
    hooks:
      - id: commit-message-validator
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=200
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
        exclude: ^tests/data/
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: pretty-format-json
        # list required for tab
        args: [--autofix, --indent, "\t", --no-ensure-ascii]
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=rst
        exclude: ^tests/data/
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: local
    hooks:
      - id: copyright
        name: check and fix copyright notice
        entry: tests/hooks/copyright_fixer.py
        files: .+\.py$
        language: python
        require_serial: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        alias: ruff
        args:
          - --fix
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --expand-star-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
        exclude: ^pywikibot/backports\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort
        exclude: ^pwb\.py$
  - repo: https://github.com/jshwi/docsig
    rev: v0.71.0
    hooks:
      - id: docsig
        exclude: ^(tests|scripts)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - --doctests
          - --config=tox.ini
        additional_dependencies:
          # Due to incompatibilities between packages the order matters.
          - flake8-bugbear>=24.12.12
          - flake8-mock-x2
          - flake8-print>=5.0.0
          - flake8-tuple>=0.4.1
          - pep8-naming>=0.15.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
          - --config-file=pyproject.toml
          - --follow-imports=silent
        additional_dependencies:
          - types-PyMySQL
          - types-requests
        # Test for files which already passed in past.
        # They should be also used in conftest.py to exclude them from non-voting mypy test.
        files: |
          (?x)^pywikibot/(
            (__metadata__|backports|config|cosmetic_changes|daemonize|diff|echo|exceptions|fixes|logging|plural|time|titletranslate)|
            (comms|data|families|specialbots)/__init__|
            comms/eventstreams|
            data/(api/(__init__|_optionset)|citoid|memento|wikistats)|
            families/[a-z][a-z\d]+_family|
            page/(__init__|_decorators|_page|_revision)|
            pagegenerators/(__init__|_filters)|
            scripts/(?:i18n/)?__init__|
            site/(__init__|_basesite|_decorators|_interwikimap|_tokenwallet|_upload)|
            tools/(_deprecate|_logging|_unidata|chars|formatter)|
            userinterfaces/(__init__|_interface_base|buffer_interface|terminal_interface|transliteration)
          )\.py$
