# -*- coding: utf-8  -*-
from pywikibot import family
    
# The Uncyclopaedia family, a satirical set of encyclopaedia wikis.
#

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'uncyclopedia'
    
        self.langs = {
            "ar": "beidipedia.wikia.com",
            "ast": "nunyepedia.wikia.com",
            "ca": "valenciclopedia.wikia.com",
            "cs": "necyklopedie.wikia.com",
            "da": "spademanns.wikia.com",
            "de": "de.uncyclopedia.org",
            "el": "frikipaideia.wikia.com", 
            "en": "uncyclopedia.org", 
            "eo": "neciklopedio.wikia.com", 
            "es": "inciclopedia.wikia.com", 
            "fa": "fa.uncyc.org", 
            "fi": "hiki.pedia.ws", 
            "fr": "desencyclopedie.wikia.com", 
            "he": "eincyclopedia.wikia.com", 
            "hr": "hr.neciklopedija.org", 
            "hu": "unciklopedia.org", 
            "id": "tolololpedia.wikia.com", 
            "it": "nonciclopedia.wikia.com", 
            "ja": "ja.uncyclopedia.info", 
            "ko": "ko.uncyclopedia.info", 
            "la": "uncapaedia.wikia.com", 
            "lt": "nesamopedija.wikia.com", 
            "lv": "lv.neciklopedija.org", 
            "nl": "oncyclopedia.net", 
            "nn": "ikkepedia.org", 
            "no": "ikkepedia.wikia.com", 
            "pl": "nonsensopedia.wikia.com", 
            "pt": "desciclo.pedia.ws", 
            "ru": "absurdopedia.wikia.com", 
            "sk": "necyklopedia.wikia.com", 
            "sl": "butalo.pedija.org", 
            "sr": "sr.neciklopedija.org", 
            "sv": "psyklopedin.org", 
            "th": "th.uncyclopedia.info", 
            "tr": "yansiklopedi.org", 
            "yi": "keinziklopedie.wikia.com", 
            "zh": "zh.uncyclopedia.wikia.com", 
            "zh-hk": "zh.uncyclopedia.info", 
            "zh-tw": "zh.uncyclopedia.info",
        }
    
        # Most namespaces are inherited from family.Family.
        self.namespaces[1] = {
            '_default': u'Talk',
            'ar': u'نقاش',
            'ast': u'Discusión',
            'ca': u'Discussió',
            'cs': u'Diskuse',
            'da': u'Diskussion',
            'de': u'Diskussion',
            'el': u'Συζήτηση',
            'en': u'Talk',
            'eo': u'Diskuto',
            'es': u'Discusión',
            'fa': u'بحث',
            'fi': u'Keskustelu',
            'fr': u'Discuter',
            'he': u'שיחה',
            'hr': u'Razgovor',
            'hu': u'Vita',
            'id': u'Pembicaraan',
            'it': u'Discussione',
            'ko': u'토론',
            'la': u'Disputatio',
            'lt': u'Aptarimas',
            'lv': u'Diskusija',
            'nl': u'Overleg',
            'nn': u'Diskusjon',
            'no': u'Diskusjon',
            'pl': u'Dyskusja',
            'pt': u'Discussão',
            'ru': u'Обсуждение',
            'sk': u'Diskusia',
            'sl': u'Pogovor',
            'sr': u'Разговор',
            'sv': u'Diskussion',
            'th': u'พูดคุย',
            'tr': u'Tartışma',
            'yi': u'רעדן',
            'zh-hk': u'討論',
            'zh-tw': u'討論',
        }

        self.namespaces[2] = {
            '_default': u'User',
            'ar': u'مستخدم',
            'ast': u'Usuariu',
            'ca': u'Usuari',
            'cs': u'Uživatel',
            'da': u'Bruger',
            'de': u'Benutzer',
            'el': u'Χρήστης',
            'en': u'User',
            'eo': u'Vikipediisto',
            'es': u'Usuario',
            'fa': u'کاربر',
            'fi': u'Käyttäjä',
            'fr': u'Utilisateur',
            'he': u'משתמש',
            'hr': u'Suradnik',
            'id': u'Pengguna',
            'it': u'Utente',
            'ja': u'利用者',
            'ko': u'사용자',
            'la': u'Usor',
            'lt': u'Naudotojas',
            'lv': u'Lietotājs',
            'nl': u'Gebruiker',
            'nn': u'Bruker',
            'no': u'Bruker',
            'pl': u'Użytkownik',
            'pt': u'Usuário',
            'ru': u'Участник',
            'sk': u'Redaktor',
            'sl': u'Uporabnik',
            'sr': u'Корисник',
            'sv': u'Användare',
            'th': u'ผู้ใช้',
            'tr': u'Kullanıcı',
            'yi': u'באַניצער',
            'zh-hk': u'用戶',
            'zh-tw': u'用戶',
        }

        self.namespaces[3] = {
            '_default': u'User talk',
            'ar': u'نقاش المستخدم',
            'ast': u'Usuariu discusión',
            'ca': u'Usuari Discussió',
            'cs': u'Uživatel diskuse',
            'da': u'Brugerdiskussion',
            'de': u'Benutzer Diskussion',
            'el': u'Συζήτηση χρήστη',
            'en': u'User talk',
            'eo': u'Vikipediista diskuto',
            'es': u'Usuario Discusión',
            'fa': u'بحث کاربر',
            'fi': u'Keskustelu käyttäjästä',
            'fr': u'Discussion Utilisateur',
            'he': u'שיחת משתמש',
            'hr': u'Razgovor sa suradnikom',
            'id': u'Pembicaraan Pengguna',
            'it': u'Discussioni utente',
            'ja': u'利用者‐会話',
            'ko': u'사용자토론',
            'la': u'Disputatio Usoris',
            'lt': u'Naudotojo aptarimas',
            'lv': u'Lietotāja diskusija',
            'nl': u'Overleg gebruiker',
            'nn': u'Brukerdiskusjon',
            'no': u'Brukerdiskusjon',
            'pl': u'Dyskusja użytkownika',
            'pt': u'Usuário Discussão',
            'ru': u'Обсуждение участника',
            'sk': u'Diskusia s redaktorom',
            'sl': u'Uporabniški pogovor',
            'sr': u'Разговор са корисником',
            'sv': u'Användardiskussion',
            'th': u'คุยกับผู้ใช้',
            'tr': u'Kullanıcı mesaj',
            'yi': u'באַניצער רעדן',
            'zh-hk': u'用戶討論',
            'zh-tw': u'用戶討論',
        }

        self.namespaces[4] = {
            '_default': u'Uncyclopedia',
            'ar': u'بيضيپيديا',
            'ast': u'Nunyepedia',
            'ca': u'Valenciclopèdia',
            'cs': u'Necyklopedie',
            'da': u'Spademanns Leksikon',
            'de': u'Uncyclopedia',
            'el': u'Φρικηπαίδεια',
            'en': u'Uncyclopedia',
            'eo': u'Neciklopedio',
            'es': u'Inciclopedia',
            'fi': u'Hikipedia',
            'fr': u'Désencyclopédie',
            'he': u'איןציקלופדיה',
            'hr': u'Neciklopedija',
            'hu': u'Unciklopédia',
            'id': u'Tolololpedia',
            'it': u'Nonciclopedia',
            'ko': u'백괴사전',
            'la': u'Uncapaedia',
            'lt': u'Nesamopedija Wiki',
            'lv': u'Neciklopēdija',
            'nl': u'Oncyclopedie',
            'nn': u'Ikkepedia',
            'no': u'Ikkepedia ',
            'pl': u'Nonsensopedia',
            'pt': u'Desciclopédia',
            'ru': u'Абсурдопедия',
            'sk': u'Necyklopédia',
            'sl': u'Butalopedija',
            'sr': u'Нециклопедија',
            'sv': u'Psyklopedin',
            'th': u'ไร้สาระนุกรม',
            'tr': u'Yansiklopedi',
            'yi': u'קיינציקלאָפעדיע',
            'zh': u'伪基百科',
            'zh-hk': u'偽基百科',
            'zh-tw': u'偽基百科',
        }
        self.namespaces[5] = {
            '_default': u'Uncyclopedia talk',
            'ar': u'نقاش بيضيپيديا',
            'ast': u'Nunyepedia discusión',
            'ca': u'Valenciclopèdia Discussió',
            'cs': u'Necyklopedie diskuse',
            'da': u'Spademanns Leksikon-diskussion',
            'de': u'Uncyclopedia Diskussion',
            'el': u'Φρικηπαίδεια συζήτηση',
            'en': u'Uncyclopedia talk',
            'eo': u'Neciklopedio diskuto',
            'es': u'Inciclopedia Discusión',
            'fa': u'بحث Uncyclopedia',
            'fi': u'Keskustelu Hikipediasta',
            'fr': u'Discussion Désencyclopédie',
            'he': u'שיחת איןציקלופדיה',
            'hr': u'Razgovor Neciklopedija',
            'hu': u'Unciklopédia vita',
            'id': u'Pembicaraan Tolololpedia',
            'it': u'Discussioni Nonciclopedia',
            'ko': u'백괴사전토론',
            'la': u'Disputatio Uncapaediae',
            'lt': u'Nesamopedija Wiki aptarimas',
            'lv': u'Neciklopēdija diskusija',
            'nl': u'Overleg Oncyclopedie',
            'nn': u'Ikkepedia-diskusjon',
            'no': u'Ikkepedia -diskusjon',
            'pl': u'Dyskusja Nonsensopedia',
            'pt': u'Desciclopédia Discussão',
            'ru': u'Обсуждение Абсурдопедии',
            'sk': u'Diskusia k Necyklopédia',
            'sl': u'Pogovor o Butalopedija',
            'sr': u'Разговор о Нециклопедија',
            'sv': u'Psyklopedindiskussion',
            'th': u'คุยเรื่องไร้สาระนุกรม',
            'tr': u'Yansiklopedi tartışma',
            'yi': u'קיינציקלאָפעדיע רעדן',
            'zh': u'伪基百科 talk',
            'zh-hk': u'偽基百科討論',
            'zh-tw': u'偽基百科討論',
        }

        self.namespaces[6] = {
            '_default': u'Image',
            'ar': u'صورة',
            'ast': u'Imaxen',
            'ca': u'Imatge',
            'cs': u'Soubor',
            'da': u'Billede',
            'de': u'Bild',
            'el': u'Εικόνα',
            'eo': u'Dosiero',
            'es': u'Imagen',
            'fa': u'تصویر',
            'fi': u'Kuva',
            'he': u'תמונה',
            'hr': u'Slika',
            'hu': u'Kép',
            'id': u'Berkas',
            'it': u'Immagine',
            'ko': u'그림',
            'la': u'Imago',
            'lt': u'Vaizdas',
            'lv': u'Attēls',
            'nl': u'Afbeelding',
            'nn': u'Bilde',
            'no': u'Bilde',
            'pl': u'Grafika',
            'pt': u'Imagem',
            'ru': u'Изображение',
            'sk': u'Obrázok',
            'sl': u'Slika',
            'sr': u'Слика',
            'sv': u'Bild',
            'th': u'ภาพ',
            'tr': u'Resim',
            'yi': u'בילד',
            'zh-hk': u'圖像',
            'zh-tw': u'圖像',
        }

        self.namespaces[7] = {
            '_default': u'Image talk',
            'ar': u'نقاش الصورة',
            'ast': u'Imaxen discusión',
            'ca': u'Imatge Discussió',
            'cs': u'Soubor diskuse',
            'da': u'Billeddiskussion',
            'de': u'Bild Diskussion',
            'el': u'Συζήτηση εικόνας',
            'eo': u'Dosiera diskuto',
            'es': u'Imagen Discusión',
            'fa': u'بحث تصویر',
            'fi': u'Keskustelu kuvasta',
            'fr': u'Discussion Image',
            'he': u'שיחת תמונה',
            'hr': u'Razgovor o slici',
            'hu': u'Kep vita',
            'id': u'Pembicaraan Berkas',
            'it': u'Discussioni immagine',
            'ja': u'画像‐ノート',
            'ko': u'그림토론',
            'la': u'Disputatio Imaginis',
            'lt': u'Vaizdo aptarimas',
            'lv': u'Attēla diskusija',
            'nl': u'Overleg afbeelding',
            'nn': u'Bildediskusjon',
            'no': u'Bildediskusjon',
            'pl': u'Dyskusja grafiki',
            'pt': u'Imagem Discussão',
            'ru': u'Обсуждение изображения',
            'sk': u'Diskusia k obrázku',
            'sl': u'Pogovor o sliki',
            'sr': u'Разговор о слици',
            'sv': u'Bilddiskussion',
            'th': u'คุยเรื่องภาพ',
            'tr': u'Resim tartışma',
            'yi': u'בילד רעדן',
            'zh-hk': u'圖像討論',
            'zh-tw': u'圖像討論',
        }

        self.namespaces[8] = {
            '_default': u'MediaWiki',
            'ar': u'ميدياويكي',
            'fa': u'مدیاویکی',
            'he': u'מדיה ויקי',
            'sr': u'МедијаВики',
            'th': u'มีเดียวิกิ',
            'tr': u'MedyaViki',
            'yi': u'מעדיעװיקי',
            'zh-hk': u'媒體偽基',
            'zh-tw': u'媒體偽基',
        }

        self.namespaces[9] = {
            '_default': u'MediaWiki talk',
            'ar': u'نقاش ميدياويكي',
            'ast': u'MediaWiki discusión',
            'ca': u'MediaWiki Discussió',
            'cs': u'MediaWiki diskuse',
            'da': u'MediaWiki-diskussion',
            'de': u'MediaWiki Diskussion',
            'eo': u'MediaWiki diskuto',
            'es': u'MediaWiki Discusión',
            'fa': u'بحث مدیاویکی',
            'fi': u'Keskustelu MediaWiki',
            'fr': u'Discussion MediaWiki',
            'he': u'שיחת מדיה ויקי',
            'hr': u'MediaWiki razgovor',
            'id': u'Pembicaraan MediaWiki',
            'it': u'Discussioni MediaWiki',
            'ja': u'MediaWiki‐ノート',
            'ko': u'MediaWiki토론',
            'la': u'Disputatio MediaWiki',
            'lt': u'MediaWiki aptarimas',
            'lv': u'MediaWiki diskusija',
            'nl': u'Overleg MediaWiki',
            'nn': u'MediaWiki-diskusjon',
            'no': u'MediaWiki-diskusjon',
            'pl': u'Dyskusja MediaWiki',
            'pt': u'MediaWiki Discussão',
            'ru': u'Обсуждение MediaWiki',
            'sk': u'Diskusia k MediaWiki',
            'sl': u'Pogovor o MediaWiki',
            'sr': u'Разговор о МедијаВикију',
            'sv': u'MediaWiki diskussion',
            'th': u'คุยเรื่องมีเดียวิกิ',
            'tr': u'MedyaViki tartışma',
            'yi': u'מעדיעװיקי רעדן',
            'zh-hk': u'媒體偽基討論',
            'zh-tw': u'媒體偽基討論',
        }

        #
        # Custom namespace list for en: (and fi:)
        #
        self.namespaces[100] = {
            '_default': u'Wilde',
            'de': u'UnNews',
            'en': u'Wilde',
            'fi': u'Hikiquote',
            'nn': u'Ikkenytt',
            'pl': u'Cytaty',
            'sv': u'PsykNyheter',
            'tr': u'YanSözlük',
        }
        self.namespaces[101] = {
            '_default': u'Wilde talk',
            'de': u'UnNews Diskussion',
            'en': u'Wilde talk',
            'nn': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'sv': u'PsykNyheter diskussion',
            'tr': u'YanSözlük tartışma',
        }
        self.namespaces[102] = {
            '_default': u'UnNews',
            'de': u'Undictionary',
            'en': u'UnNews',
            'nn': u'Ikktionary',
            'pl': u'NonNews',
            'sv': u'Forum',
            'tr': u'YanHaber',
        }
        self.namespaces[103] = {
            'de': u'Undictionary Diskussion',
            'en': u'UnNews talk',
            'ja': u'UnNews talk',
            'nn': u'Ikktionary-diskusjon',
            'pl': u'Dyskusja NonNews',
            'sv': u'Forumdiskussion',
            'tr': u'YanHaber tartışma',
        }
        self.namespaces[104] = {
            'de': u'UnBooks',
            'en': u'Undictionary',
            'pl': u'Nonźródła',
            'sv': u'Psyktionary',
        }
        self.namespaces[105] = {
            'de': u'UnBooks Diskussion',
            'en': u'Undictionary talk',
            'pl': u'Dyskusja nonźródeł',
            'sv': u'Psyktionary diskussion',
        }
        self.namespaces[106] = {
            'en': u'Game',
            'ja': u'Game',
            'pl': u'Słownik',
            'pt': u'Desnotícias',
            'sv': u'PsykCitat',
        }
        self.namespaces[107] = {
            'en': u'Game talk',
            'ja': u'Game talk',
            'pl': u'Dyskusja słownika',
            'pt': u'Desnotícias Discussão',
            'sv': u'PsykCitat diskussion',
        }
        self.namespaces[108] = {
            'en': u'Babel',
            'pl': u'Gra',
            'pt': u'Jogo',
            'sv': u'Spel',
        }
        self.namespaces[109] = {
            'en': u'Babel talk',
            'pl': u'Dyskusja gry',
            'pt': u'Jogo Discussão',
            'sv': u'Speldiskussion',
        }
        self.namespaces[110] = {
            'ar': u'Forum',
            'ast': u'Forum',
            'ca': u'Forum',
            'cs': u'Forum',
            'da': u'Forum',
            'de': u'Forum',
            'el': u'Forum',
            'en': u'Forum',
            'eo': u'Forum',
            'es': u'Forum',
            'fr': u'Forum',
            'he': u'Forum',
            'id': u'Forum',
            'it': u'Forum',
            'ja': u'Forum',
            'la': u'Forum',
            'lt': u'Forum',
            'nn': u'Forum',
            'no': u'Forum',
            'pl': u'Forum',
            'pt': u'Descionário',
            'ru': u'Форум',
            'sk': u'Forum',
            'sv': u'PsykBöcker',
            'tr': u'Astroloji',
            'yi': u'Forum',
            'zh': u'Forum',
        }
        self.namespaces[111] = {
            'ar': u'Forum talk',
            'ast': u'Forum talk',
            'ca': u'Forum talk',
            'cs': u'Forum talk',
            'da': u'Forumdiskussion',
            'de': u'Forum talk',
            'el': u'Forum talk',
            'en': u'Forum talk',
            'eo': u'Forum talk',
            'es': u'Forum talk',
            'fr': u'Discussion Forum',
            'he': u'Forum talk',
            'id': u'Forum talk',
            'it': u'Forum talk',
            'ja': u'Forum talk',
            'la': u'Forum talk',
            'lt': u'Forum talk',
            'nn': u'Forum-diskusjon',
            'no': u'Forum talk',
            'pl': u'Dyskusja forum',
            'pt': u'Descionário Discussão',
            'ru': u'Обсуждение форума',
            'sk': u'Forum talk',
            'sv': u'PsykBöckerdiskussion',
            'tr': u'Astroloji tartışma',
            'yi': u'Forum talk',
            'zh': u'Forum talk',
        }

        # A few selected big languages for things that we do not want to loop over
        # all languages. This is only needed by the titletranslate.py module, so
        # if you carefully avoid the options, you could get away without these
        # for another wiki family.
        self.languages_by_size = ['en', 'pl', 'de', 'es', 'ru', 'fr']

    def hostname(self,code):
        return self.langs[code]

    def scriptpath(self, code):
        return ''

    def version(self, code):
        return "1.12alpha"
