---
# Run GraalPy tests with a variety of GraalPy versions and os
name: GraalPy Tests

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYWIKIBOT_TEST_RUNNING: 1
  PYWIKIBOT_USERNAME: Pywikibot-test

jobs:
  build:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    continue-on-error: ${{ matrix.experimental || false }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        python-version: [graalpy-23.1, graalpy-24.2, graalpy-25.0]
        os: [macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: ${{ endsWith(matrix.python-version, '-dev') }}
          cache: pip
          cache-dependency-path: .github/requirements/graalpy_tests.txt
      - name: Install dependencies
        run: |
          pip --version
          pip install -r .github/requirements/graalpy_tests.txt
      - name: Install setuptools
        if: ${{ startsWith(matrix.python-version, 'graalpy-25') }}
        run: pip install setuptools
      - name: Generate user files
        run: |
          python -Werror::UserWarning -m pwb generate_user_files -site:wikipedia:test -v -debug;
      - name: Test with pytest
        id: ci_test
        continue-on-error: true
        env:
          PYTHONWARNINGS: ignore:urllib3 v2 only supports OpenSSL
          PYTHONIOENCODING: utf-8
          PYWIKIBOT_TEST_NO_RC: 1
        run: |
          python pwb.py version
          if [[  "${{ matrix.python-version }}" == "graalpy-25.0" && "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "Running tests without coverage"
            pytest -k "not TestDate" -a "not net" --ignore=tests/script_tests.py
          else
            echo "Running tests with coverage"
            coverage run -m pytest -k "not TestDate" -a "not net" --ignore=tests/script_tests.py
          fi
      - name: Show coverage statistics
        if: matrix.python-version != 'graalpy-25.0' || matrix.os != 'ubuntu-latest'
        run: |
          coverage combine || true
          coverage report
      - name: Upload coverage to Codecov
        if: matrix.python-version != 'graalpy-25.0' || matrix.os != 'ubuntu-latest'
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Check on failure
        if: steps.ci_test.outcome == 'failure'
        run: |-
          exit 1
